services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
  # image removed so compose will build locally from ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/foodplanner
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- --tries=1 --timeout=5 http://127.0.0.1:5000/api/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
  # image removed so compose will build locally from ./frontend
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=${VITE_API_URL}
    restart: unless-stopped

  mongo:
    image: mongo:6
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
