version: '3.8'
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/foodplanner
      - JWT_SECRET=supersecretkey
    depends_on:
      - mongo
    volumes:
      - .:/app
  mongo:
    image: mongo:6
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
